//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by X88000.rc
//
#define IDC_ADDRESS_ADD                 3
#define IDC_BREAK_POINT_REMOVE          4
#define IDC_BREAK_POINT_ERASE           5
#define IDR_MAINMENU                    101
#define IDD_TAPE_IMAGE                  102
#define IDR_MAINMENU_E                  102
#define IDI_X88000                      104
#define IDD_VERSION                     105
#define IDR_ACCELERATOR                 107
#define IDD_DISK_IMAGE                  108
#define IDD_DEBUG_BREAK_POINT           109
#define IDD_DEBUG_DIS_ASSEMBLE          110
#define IDD_DEBUG_DUMP                  111
#define IDD_ENV_GENERAL                 112
#define IDD_ENV_DISPLAY                 113
#define IDD_ENV_INPUT                   114
#define IDD_PRINTER                     115
#define IDD_ENV_SOUND                   116
#define IDD_PRINTER_PAPERDEL            117
#define IDD_PRINTER_PAPERFEED           118
#define IDD_PRINTER_COPY                119
#define IDD_DEBUG_WRITE_RAM             120
#define IDD_ENV_GENERAL_E               121
#define IDD_ENV_DISPLAY_E               122
#define IDD_ENV_INPUT_E                 123
#define IDD_ENV_SOUND_E                 124
#define IDD_PRINTER_E                   125
#define IDD_PRINTER_COPY_E              126
#define IDD_PRINTER_PAPERDEL_E          127
#define IDD_PRINTER_PAPERFEED_E         128
#define IDD_DISK_IMAGE_E                129
#define IDD_TAPE_IMAGE_E                130
#define IDD_DEBUG_DIS_ASSEMBLE_E        131
#define IDD_DEBUG_DUMP_E                132
#define IDD_DEBUG_BREAK_POINT_E         133
#define IDD_DEBUG_WRITE_RAM_E           134
#define IDD_VERSION_E                   135
#define IDC_LIMAGE_REW                  1004
#define IDC_LIMAGE_FWD                  1005
#define IDC_LIMAGE_OPEN                 1006
#define IDC_SIMAGE_SAVE                 1009
#define IDC_SIMAGE_ERASE                1010
#define IDC_LIMAGE_NAME                 1011
#define IDC_LIMAGE_INFO                 1012
#define IDC_LIMAGE_COUNTER              1013
#define IDC_SIMAGE_INFO                 1014
#define IDC_SIMAGE_COUNTER              1015
#define IDC_VERSION                     1015
#define IDC_IMAGES                      1016
#define IDC_IMAGE_ADD                   1017
#define IDC_IMAGE_REMOVE                1018
#define IDC_DISK_DRIVE1                 1020
#define IDC_DISK_DRIVE2                 1021
#define IDC_BREAK_POINT                 1021
#define IDC_ADDRESS                     1022
#define IDC_DISK_DRIVE3                 1022
#define IDC_DISK_DRIVE4                 1023
#define IDC_LINE_COUNT                  1024
#define IDC_DIS_ASSEMBLE                1025
#define IDC_DIS_ASSEMBLE_LIST           1026
#define IDC_BYTE_COUNT                  1027
#define IDC_DUMP                        1028
#define IDC_DUMP_LIST                   1029
#define IDC_BOOST_LIMITER               1030
#define IDC_DISK_DRIVE1_LABEL           1030
#define IDC_DISK_DRIVE2_LABEL           1031
#define IDC_DISK_DRIVE3_LABEL           1032
#define IDC_DISK_DRIVE4_LABEL           1033
#define IDC_IMAGE_ERASE                 1038
#define IDC_DISK_DRIVE1_PROTECT         1040
#define IDC_FRAME_RATE                  1040
#define IDC_DISK_DRIVE2_PROTECT         1041
#define IDC_INTERLACE_DO                1041
#define IDC_DISK_DRIVE3_PROTECT         1042
#define IDC_DIRECT_INPUT_USE            1042
#define IDC_INTERLACE_NODO              1042
#define IDC_DISK_DRIVE4_PROTECT         1043
#define IDC_DIRECT_INPUT_NOUSE          1043
#define IDC_PRINTER_PREVIEW             1043
#define IDC_VSYNC_24KHZ                 1043
#define IDC_DIRECT_SOUND_USE            1044
#define IDC_IME_ENABLE                  1044
#define IDC_VSYNC_15KHZ                 1044
#define IDC_DIRECT_SOUND_NOUSE          1045
#define IDC_IME_DISABLE                 1045
#define IDC_PRINTER_PAGE                1046
#define IDC_PRINTER_PAGE_SPIN           1047
#define IDC_DSOUND_FREQ                 1048
#define IDC_DISK_DRIVE_GROUP            1050
#define IDC_DSOUND_BIT                  1050
#define IDC_DSOUND_CH                   1051
#define IDC_BEEP_MUTE                   1053
#define IDC_BEEP_VOLUME                 1054
#define IDC_PRINTER_PAGE_MAX            1055
#define IDC_PRINTER_NAME                1056
#define IDC_PRINTER_PAPER               1057
#define IDC_PCG_VOLUME                  1057
#define IDC_PCG_MUTE                    1058
#define IDC_PRINTER_COPY                1059
#define IDC_PCG_GROUP                   1059
#define IDC_PRINTER_PAPER_DELETE        1060
#define IDC_PRINTER_PAPER_FEED          1061
#define IDC_PRINTER_RESET               1062
#define IDC_PRINTER_PAPER_CENTER        1063
#define IDC_PRINTER_PAPERDEL_ONEPAGE    1064
#define IDC_PRINTER_PAPERDEL_ALLPAGES   1065
#define IDC_PRINTER_PAPERDEL_PAGENO     1066
#define IDC_PRINTER_PAPERDEL_PAGENO_SPIN 1067
#define IDC_PRINTER_PAPERFEED_LINE      1068
#define IDC_PRINTER_PAPERFEED_LINE_COUNT 1069
#define IDC_PRINTER_PAPERFEED_LINE_COUNT_SPIN 1070
#define IDC_PRINTER_PAPERFEED_PAGE      1071
#define IDC_PRINTER_PAPERFEED_POINT     1072
#define IDC_PRINTER_COPY_PAGENO         1072
#define IDC_PRINTER_PAPERFEED_POINT_COUNT 1073
#define IDC_PRINTER_COPY_PAGENO_SPIN    1073
#define IDC_PRINTER_PAPERFEED_POINT_COUNT_SPIN 1074
#define IDC_PRINTER_COPY_METAFILE       1074
#define IDC_PRINTER_COPY_TEXT           1075
#define IDC_PRINTER_COPY_HOLE           1076
#define IDC_PRINTER_COPY_BORDER         1077
#define IDC_PRINTER_COPY_ZOOM           1078
#define IDC_WRITE_MAIN_RAM0             1079
#define IDC_WRITE_MAIN_RAM1             1080
#define IDC_WAIT_EMULATION              1080
#define IDC_WRITE_FAST_TVRAM            1081
#define IDC_OLD_COMPATIBLE              1081
#define IDC_WRITE_SLOW_TVRAM            1082
#define IDC_PCG_ENABLE                  1082
#define IDC_WRITE_GVRAM0                1083
#define IDC_OPTION_FONT                 1083
#define IDC_WRITE_GVRAM1                1084
#define IDC_WRITE_GVRAM2                1085
#define IDC_WRITE_SUB_RAM               1086
#define IDC_WRITE_EX_RAM0               1087
#define IDC_WRITE_EX_RAM1               1088
#define IDC_UI_LANGUAGE                 1089
#define IDM_EXIT                        40001
#define IDM_RESET                       40002
#define IDM_BASICMODE_N                 40003
#define IDM_BASICMODE_V1_S              40004
#define IDM_TAPE_IMAGE                  40005
#define IDM_VERSION                     40006
#define IDM_BOOST_MODE                  40007
#define IDM_MEMORY_IMAGE                40008
#define IDM_DISK_IMAGE                  40009
#define IDM_DEBUG_MAIN                  40010
#define IDM_DEBUG_SUB                   40011
#define IDM_DEBUG_EXECUTE               40012
#define IDM_DEBUG_EXECUTE_STEP          40013
#define IDM_DEBUG_EXECUTE_TRACE         40014
#define IDM_DEBUG_BREAK_POINT           40015
#define IDM_BASICMODE_V2                40016
#define IDM_BASICMODE_V1_H              40018
#define IDM_DEBUG_DIS_ASSEMBLE          40019
#define IDM_DEBUG_DUMP                  40020
#define IDM_DEBUG_EXECUTE_STEP2         40021
#define IDM_DEBUG_LOG                   40022
#define IDM_BASE_CLOCK_4                40023
#define IDM_BASE_CLOCK_8                40024
#define IDM_CLIPBOARD_COPY_BITMAP       40025
#define IDM_CLIPBOARD_COPY_TEXT         40026
#define IDM_CLIPBOARD_PASTE_TEXT        40027
#define IDM_FULL_SCREEN_MODE            40028
#define IDM_ENV_SET                     40029
#define IDM_PARALLEL_DEVICE_SETTING     40031
#define IDM_PARALLEL_DEVICE0            40032
#define IDM_PARALLEL_DEVICE1            40033
#define IDM_PARALLEL_DEVICE2            40034
#define IDM_PARALLEL_DEVICE3            40035
#define IDM_PARALLEL_DEVICE4            40036
#define IDM_PARALLEL_DEVICE5            40037
#define IDM_PARALLEL_DEVICE6            40038
#define IDM_PARALLEL_DEVICE7            40039
#define IDM_PARALLEL_DEVICE8            40040
#define IDM_PARALLEL_DEVICE9            40041
#define IDM_NOP                         40042
#define IDM_BASICMODE_N80_V1            40043
#define IDM_BASICMODE_N80_V2            40044
#define IDM_DEBUG_WRITE_RAM             40045
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        121
#define _APS_NEXT_COMMAND_VALUE         40046
#define _APS_NEXT_CONTROL_VALUE         1090
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
